//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerkansingSysteemPVB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docent
    {
        public Docent()
        {
            this.Herkansing = new HashSet<Herkansing>();
            this.Herkansing1 = new HashSet<Herkansing>();
        }
    
        public string DocentID { get; set; }
        public string Roepnaam { get; set; }
        public string Tussenvoegsel { get; set; }
        public string Achternaam { get; set; }
        public string Email { get; set; }
        public string Wachtwoord { get; set; }
    
        public virtual ICollection<Herkansing> Herkansing { get; set; }
        public virtual ICollection<Herkansing> Herkansing1 { get; set; }
    }
}
