//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerkansingSysteemPVB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Herkansing
    {
        public Herkansing()
        {
            this.Inschrijving = new HashSet<Inschrijving>();
        }
    
        public int HerkansingID { get; set; }
        public string Lokaal { get; set; }
        public string Docent { get; set; }
        public System.DateTime Datum { get; set; }
        public string Surveillant { get; set; }
        public int Toets { get; set; }
        public int Tijdsduur { get; set; }
        public int Plaatsen { get; set; }
        public bool Actief { get; set; }
    
        public virtual Docent Docent1 { get; set; }
        public virtual Docent Docent2 { get; set; }
        public virtual Lokaal Lokaal1 { get; set; }
        public virtual Toets Toets1 { get; set; }
        public virtual ICollection<Inschrijving> Inschrijving { get; set; }
    }
}
