//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerkansingSysteemPVB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inschrijving
    {
        public string StudentID { get; set; }
        public int HerkansingID { get; set; }
        public string BevestigingsID { get; set; }
        public bool Bevestigd { get; set; }
    
        public virtual Herkansing Herkansing { get; set; }
        public virtual Student Student { get; set; }
    }
}
