//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerkansingSysteemPVB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokaal
    {
        public Lokaal()
        {
            this.Herkansing = new HashSet<Herkansing>();
        }
    
        public string LokaalNr { get; set; }
    
        public virtual ICollection<Herkansing> Herkansing { get; set; }
    }
}
