//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerkansingSysteemPVB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toets
    {
        public Toets()
        {
            this.Herkansing = new HashSet<Herkansing>();
        }
    
        public int ToetsID { get; set; }
        public string ToetsNaam { get; set; }
        public string ToetsDescriptie { get; set; }
        public int Vak { get; set; }
    
        public virtual ICollection<Herkansing> Herkansing { get; set; }
        public virtual Vak Vak1 { get; set; }
    }
}
