//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerkansingSysteemPVB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vak
    {
        public Vak()
        {
            this.Toets = new HashSet<Toets>();
        }
    
        public int VakID { get; set; }
        public string VakNaam { get; set; }
    
        public virtual ICollection<Toets> Toets { get; set; }
    }
}
